{% set name = "geoai-py" %}
{% set version = "0.43.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/geoai_py-{{ version }}.tar.gz
  sha256: 752454030b3a6448acd2a37ee23afe1d69677641d73837f9f368a4b5ecb83677

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - albumentations
    - buildingregulariser
    - contextily
    - datasets
    - geopandas
    - huggingface_hub
    - jupyter-server-proxy
    - leafmap >=0.62.0
    - localtileserver
    - mapclassify
    - maplibre >=0.3.0
    - opencv
    - overturemaps
    - planetary-computer
    - pystac-client
    - rasterio
    - rioxarray
    - scikit-image
    - scikit-learn
    - smoothify
    - pytorch
    - torchgeo >=0.9.0
    - torchinfo
    - tqdm
    - transformers
    - typer
    - albucore >=0.1.0
    - geolibre

  run_constrained:
    - flask_cors <0a0  # prevent underscore-named package from co-installing

test:
  imports:
    - geoai
  commands:
    - pip check
  requires:
    - pip
    - libopencv * =*headless*  # [linux]
    - python {{ python_min }}
    - albucore >=0.1.0

outputs:
  - name: geoai-py
  - name: geoai
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage("geoai-py", exact=True) }}

    test:
      requires:
        - python {{ python_min }}
        - albucore >=0.1.0

      imports:
        - geoai


about:
  home: https://github.com/opengeos/geoai
  summary: A Python package for integrating Artificial Intelligence with geospatial data analysis and visualization
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
